OENIK_PROG4HF_2020_1_OY7P82/JuiceShop.Web/Models/Juice.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace JuiceShop.Web.Models
{
    public class Juice
    {
        [Display(Name = "Juice ID")]
        [Required]
        public int ID { get; set; }
        [Display(Name = "Juice BRAND")]
        [Required]
        [StringLength(100, MinimumLength = 5)]
        public string BRAND { get; set; }
        [Display(Name = "Juice MADEINCOUNTRY")]
        [Required]
        [StringLength(100, MinimumLength = 5)]
        public string MADEINCOUNTRY { get; set; }
        [Display(Name = "Juice FRUITS")]
        [Required]
        [StringLength(100, MinimumLength = 5)]
        public string FRUITS { get; set; }
        [Display(Name = "Juice PRODUCTION")]
        [Required]
        public int PRODUCTION { get; set; }
        [Display(Name = "Juice PRICE")]
        [Required]
        public int PRICE { get; set; }
        [Display(Name = "Juice PROFIT")]
        [Required]
        public int PROFIT { get; set; }
    }
}

OENIK_PROG4HF_2020_1_OY7P82/JuiceShop.Web/Models/JuicesViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace JuiceShop.Web.Models
{
    public class JuicesViewModel
    {
        public Juice EditedJuice { get; set; }
        public List<Juice> AllJuices { get; set; }
    }
}

OENIK_PROG4HF_2020_1_OY7P82/JuiceShop.Web/Controllers/JuicesController.cs
using AutoMapper;
using JuiceShop.Data;
using JuiceShop.Logic;
using JuiceShop.Repository;
using JuiceShop.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JuiceShop.Web.Controllers
{
    public class JuicesController : Controller
    {
        IJuiceLogic logic;
        IMapper mapper;
        JuicesViewModel model;
        public JuicesController()
        {
            DBEntities ctx = new DBEntities();
            JuiceRepository repository = new JuiceRepository(ctx);
            logic = new JuiceLogic(repository);
            mapper = MapperFactory.CreateMapper();
            model = new JuicesViewModel();
            model.EditedJuice = new Juice();
            model.AllJuices = mapper.Map<IList<Data.JUICE>, List<Models.Juice>>(logic.GetAllJuices());
        }

        private Juice GetJuice(int d)
        {
            var kek = logic.GetOneJuice(d);
            return mapper.Map<Data.JUICE, Models.Juice>(kek);
        }
        // GET: Juices
        public ActionResult Index()
        {
            ViewData["editAction"] = "AddNew";
            return View("JuicesIndex", model);
        }
        // GET: Juices/Details/5
        public ActionResult Details(int id)
        {
            return View("JuicesDetails", GetJuice(id));
        }
        public ActionResult Remove(int id)
        {
            TempData["editResult"] = "Delete FAIL";
            if (logic.RemoveJuice(id)) TempData["editResult"] = "Delete OK";
            return RedirectToAction("Index");
        }
        public ActionResult Edit(int id)
        {
            ViewData["editAction"] = "Edit";
            model.EditedJuice = this.GetJuice(id);
            return View("JuicesIndex", model);
        }
        [HttpPost]
        public ActionResult Edit(Juice juice, string editAction)
        {
            if (ModelState.IsValid && juice != null)
            {
                TempData["editResult"] = "Edit OK";
                if (editAction == "AddNew")
                {
                    logic.AddJuice(juice.BRAND, juice.MADEINCOUNTRY, juice.FRUITS, juice.PRODUCTION, juice.PRICE, juice.PROFIT);
                }
                else
                {
                    bool succss = logic.ChangeJuice(juice.ID, juice.BRAND, juice.MADEINCOUNTRY, juice.FRUITS, juice.PRODUCTION, juice.PRICE, juice.PROFIT);
                    if (!succss) TempData["editResult"] = "Edit FAIL";
                }
                return RedirectToAction(nameof(Index));
            }
            else
            {
                ViewData["editAction"] = "Edit";
                model.EditedJuice = juice;
                return View("JuicesIndex", model);
            }
        }

    }
}

OENIK_PROG4HF_2020_1_OY7P82/JuiceShop.Web/Views/Juices/JuicesDetails.cshtml
@model JuiceShop.Web.Models.Juice
@{
    ViewBag.Title = "JuicesDetails";
}

<h2>Datasheet of one Juice</h2>

@Html.ActionLink("Back to the list", "Index");

<table border="1">
    <tr>
        <td>The ID of the Juice</td>
        <td>@Model.ID</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.BRAND)</td>
        <td>@Html.DisplayFor(m => m.BRAND)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.MADEINCOUNTRY)</td>
        <td>@Html.DisplayFor(m => m.MADEINCOUNTRY)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.FRUITS)</td>
        <td>@Html.DisplayFor(m => m.FRUITS)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.PRICE)</td>
        <td>@Html.DisplayFor(m => m.PRICE)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.PRODUCTION)</td>
        <td>@Html.DisplayFor(m => m.PRODUCTION)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.PROFIT)</td>
        <td>@Html.DisplayFor(m => m.PROFIT)</td>
    </tr>
</table>

OENIK_PROG4HF_2020_1_OY7P82/JuiceShop.Web/Views/Juices/JuicesEdit.cshtml
@model JuiceShop.Web.Models.Juice
@{
    ViewBag.Title = "JuicesEdit";
}

<h2>Edit one Juice</h2>

@using (Html.BeginForm("Edit", "Juices"))
{
    @Html.ValidationSummary()

    @Html.AntiForgeryToken()

    @Html.HiddenFor(m => m.ID)
    @Html.Hidden("editAction", ViewData["editAction"].ToString());

    <div class="editor-label">@Html.LabelFor(m => m.BRAND)</div>
    <div class="editor-label">@Html.EditorFor(m => m.BRAND)</div>
    <div class="editor-label">@Html.LabelFor(m => m.MADEINCOUNTRY)</div>
    <div class="editor-label">@Html.EditorFor(m => m.MADEINCOUNTRY)</div>
    <div class="editor-label">@Html.LabelFor(m => m.FRUITS)</div>
    <div class="editor-label">@Html.EditorFor(m => m.FRUITS)</div>
    <div class="editor-label">@Html.LabelFor(m => m.PRICE)</div>
    <div class="editor-label">@Html.EditorFor(m => m.PRICE)</div>
    <div class="editor-label">@Html.LabelFor(m => m.PRODUCTION)</div>
    <div class="editor-label">@Html.EditorFor(m => m.PRODUCTION)</div>
    <div class="editor-label">@Html.LabelFor(m => m.PROFIT)</div>
    <div class="editor-label">@Html.EditorFor(m => m.PROFIT)</div>

    <input type="submit" value="SEND" />
}

OENIK_PROG4HF_2020_1_OY7P82/JuiceShop.Web/Views/Juices/JuicesIndex.cshtml
@model JuiceShop.Web.Models.JuicesViewModel
@{
    ViewBag.Title = "JuicesIndex";
}

<h2>JuicesIndex</h2>

<p style="color:red; font-weight:bold">@TempData["editResult"]</p>

@Html.Partial("JuicesEdit", Model.EditedJuice)

@Html.Partial("JuicesList", Model.AllJuices)

OENIK_PROG4HF_2020_1_OY7P82/JuiceShop.Web/Views/Juices/JuicesList.cshtml
@model IEnumerable<JuiceShop.Web.Models.Juice>
@{
    ViewBag.Title = "JuicesList";
}

<h2>List of Juices</h2>

@if (Model.Count() == 0)
{
    <p>No data in the database</p>
}
else
{
    <table border="1">
        <tr>
            <th>@Html.DisplayNameFor(m => m.First().ID)</th>
            <th>@Html.DisplayNameFor(m => m.First().BRAND)</th>
            <th>@Html.DisplayNameFor(m => m.First().MADEINCOUNTRY)</th>
            <th>@Html.DisplayNameFor(m => m.First().FRUITS)</th>
            <th>@Html.DisplayNameFor(m => m.First().PRICE)</th>
            <th>@Html.DisplayNameFor(m => m.First().PRODUCTION)</th>
            <th>@Html.DisplayNameFor(m => m.First().PROFIT)</th>
            <th>Datasheet</th>
            <th>Delete</th>
            <th>Edit</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(m => item.ID)</td>
                <td>@Html.DisplayFor(m => item.BRAND)</td>
                <td>@Html.DisplayFor(m => item.MADEINCOUNTRY)</td>
                <td>@Html.DisplayFor(m => item.FRUITS)</td>
                <td>@Html.DisplayFor(m => item.PRICE)</td>
                <td>@Html.DisplayFor(m => item.PRODUCTION)</td>
                <td>@Html.DisplayFor(m => item.PROFIT)</td>
                <td>@Html.ActionLink("[SHOW]", "Details", new { id = item.ID })</td>
                <td>@Html.ActionLink("[DEL]", "Remove", new { id = item.ID })</td>
                <td>@Html.ActionLink("[EDIT]", "Edit", new { id = item.ID })</td>
            </tr>
        }
    </table>
}